#ifndef _CONFIG_H_
#define _CONFIG_H_

#define INTERFACE_TASK_PRIORITY (1U)
#define INTERFACE_TASK_STACK    (3 * configMINIMAL_STACK_SIZE)

#define CMDSVR_TASK_PRIORITY (2U)
#define CMDSVR_TASK_STACK    (configMINIMAL_STACK_SIZE)

#endif /* _CONFIG_H_ */