#ifndef _CONFIG_H_
#define _CONFIG_H_

#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 1

#define APP_TASK_PRIORITY (1U)
#define APP_TASK_STACK    (4 * configMINIMAL_STACK_SIZE)

#define INTERFACE_TASK_PRIORITY (2U)
#define INTERFACE_TASK_STACK    (2 * configMINIMAL_STACK_SIZE)

#define CMDSVR_TASK_PRIORITY (3U)
#define CMDSVR_TASK_STACK    (2 * configMINIMAL_STACK_SIZE)

#endif /* _CONFIG_H_ */